# 项目相关配置
stackoak:
  # 名称
  name: StackOak
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2025
  # 文件路径
  profile: /Users/liuxin/Desktop/stackoak/uploadPath
  api:
    admin:
      prefix: /admin
      package: com.stackoak.stackoak.application.controller.admin
    portal:
      prefix: /portal
      package: com.stackoak.stackoak.application.controller.portal
api-package: com.stackoak.stackoak.application.controller.portal
server:
  port: 9856
spring:
  datasource:
    url: jdbc:mysql://124.221.53.234:3306/xilio1024?serverTimezone=UTC
    username: xilio1024
    password: EbfSKppBwZMemEGW
    driverClassName: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    ssl:
      enabled: false
    username: xilio1024@163.com
    password: WV5Db9gqbFKHn9hw
    port: 465
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  data:
    redis:
      host: localhost
      port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

