# 项目相关配置
stackoak:
  # 名称
  name: StackOak
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2025
  # 文件路径
  profile: /Users/liuxin/Desktop/stackoak/uploadPath
  fileUploadModel: Minio
  api:
    admin:
      prefix: /admin
      package: com.stackoak.stackoak.application.controller.admin
    portal:
      prefix: /portal
      package: com.stackoak.stackoak.application.controller.portal
server:
  port: 9856

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.163.com
    ssl:
      enabled: false
    username: xilio1024@163.com
    password: WV5Db9gqbFKHn9hw
    port: 465
  # 文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128

  # 是否输出操作日志
  is-log: true

redis:
  mq:
    streams:
      # 消息通知
      - name: STACKOAK:MESSAGES:NOTIFICATION
        groups:
          - name: NOTIFICATION_GROUP
            consumers: NOTIFICATION_CONSUMER_1

